### PR TITLE
[Polymetis] Update persist_server.sh

### PR DESCRIPTION
**Pull request by 1heart**
# Description

- Correctly load conda env from parent env in `persist_server.sh`
- Save server-restarting logs in same file as server logs, for easier debugging
- Re-add alephzero as Polymetis dependency

## Type of change

Please check the options that are relevant.

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [ ] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change
- [ ] Datasets Release
- [ ] Models Release

## Type of requested review

- [ ] I want a thorough review of the implementation.
- [ ] I want a high level review. 
- [ ] I want a deep design review.

## Before and After

If this PR introduces a change or fixes a bug, please add before and after screenshots (if this is causes a UX change) or before and after examples(this could be plain text, videos etc ) to demonstrate the change.

If this PR introduces a new feature, please also add examples or screenshots demonstrating the feature.

# Testing

Please describe the tests that you ran to verify your changes and how we can reproduce.

# Checklist:

- [ ] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added relevant collaborators to review the PR before merge.
- [ ] [Polymetis only] I ran on hardware (1) all scripts in `tests/scripts`, (2) asv benchmarks.

### CODE REVIEW

**Review by girifb — APPROVED** [review]

**Comment by AlexanderKhazatsky** [comment]
Could you guys write an equivalent version for launching the gripper servers by chance :)

**Comment by AlexanderKhazatsky** [comment]
Also, if I want to launch a server with a subprocess in python, would this be the right approach?

**Comment by 1heart** [comment]
Are your gripper servers dying at a high enough frequency for this to be an issue?

The `persist_server.sh` script is a way to automatically restart the server in case it dies by using a heartbeat; I don't think it's super relevant for launching servers with subprocesses, but if you have a particular usecase in mind, feel free to make an issue.

**Comment by AlexanderKhazatsky** [comment]
The launch gripper file tends to need a variable amount of launches before it works. Sometimes it works on the first go, other times it fails, needs to be launched a second time, then works perfectly (also could be something to look into)

**Comment by 1heart** [comment]
@AlexanderKhazatsky we don't observe this behavior in our lab (primarily with Robotiq-2F; cc @Jdvakil). If you have more details (i.e. which gripper, any context when the gripper server dies, etc.), please do make an Issue so we can properly track & resolve it.

**Comment by AlexanderKhazatsky** [comment]
It’s with the robotiq gripper, and we’re also observing this issue across people and robot setups. One important detail could be that we use polymetis-local (the repo setup)

**Comment by 1heart** [comment]
@Jdvakil can you try reproducing this in the lab? I haven't noticed this happening, and wouldn't know why there'd be any difference for the gripper between conda vs. local builds.

**Pull request merged**
