### PR TITLE
[Polymetis] Fix modbus exception handling

### LINKED ISSUE #1383: Minor Issue with Robotiq Gripper
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description
Hi all,

I just started using a robotiq gripper with polymetis, but after a while I noticed that the server throws an error and fails. The issue is resolved by restarting the server but I thought it would be worth mentioning.

## Current Behavior

Running the command to use the robotiq gripper ` launch_gripper.py gripper=robotiq_2f gripper.comport=/dev/ttyUSB0   `
returns the following error

```
Warning: Failed to load 'libtorchscript_pinocchio.so' from CONDA_PREFIX, loading from default build directory instead: '/home/panda5/fairo/polymetis/polymet
is/build/torch_isolation/libtorchscript_pinocchio.so'
Warning: Failed to load 'libtorchrot.so' from CONDA_PREFIX, loading from default build directory instead: '/home/panda5/fairo/polymetis/polymetis/build/torc
h_isolation/libtorchrot.so'
/home/panda5/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/hydra/plugins/config_source.py:190: UserWarning:
Missing @package directive gripper/robotiq_2f.yaml in pkg://polymetis.conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
Gripper server running at 0.0.0.0:50052.
Activating gripper...
Activated.
Traceback (most recent call last):
  File "/home/panda5/fairo/polymetis/polymetis/python/scripts/launch_gripper.py", line 40, in main
    gripper_client.run()
  File "/home/panda5/fairo/polymetis/polymetis/python/polymetis/robot_client/robotiq_gripper/robotiq_gripper_client.py", line 94, in run
    state = self.get_gripper_state()
  File "/home/panda5/fairo/polymetis/polymetis/python/polymetis/robot_client/robotiq_gripper/robotiq_gripper_client.py", line 69, in get_gripper_state
    self.gripper.getStatus()
  File "/home/panda5/fairo/polymetis/polymetis/python/polymetis/robot_client/robotiq_gripper/third_party/robotiq_2finger_grippers/robotiq_2f_gripper.py", li
ne 64, in getStatus
    status = self.client.getStatus(6)
  File "/home/panda5/fairo/polymetis/polymetis/python/polymetis/robot_client/robotiq_gripper/third_party/robotiq_2finger_grippers/robotiq_modbus_rtu/comModb
usRtu.py", line 122, in getStatus
    output.append((response.getRegister(i) & 0xFF00) >> 8)
AttributeError: 'ModbusIOException' object has no attribute 'getRegister'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
## Expected Behavior
Successful terminal looks like this
```
launch_gripper.py gripper=robotiq_2f gripper.comport=/dev/ttyUSB0
Warning: Failed to load 'libtorchscript_pinocchio.so' from CONDA_PREFIX, loading from default build directory instead: '/home/panda5/fairo/polymetis/polymetis/build/torch_isolation/libtorchscript_pinocchio.so'
Warning: Failed to load 'libtorchrot.so' from CONDA_PREFIX, loading from default build directory instead: '/home/panda5/fairo/polymetis/polymetis/build/torch_isolation/libtorchrot.so'
/home/panda5/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/hydra/plugins/config_source.py:190: UserWarning:
Missing @package directive gripper/robotiq_2f.yaml in pkg://polymetis.conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
Gripper server running at 0.0.0.0:50052.
Activating gripper...
Activated.

```
## Steps to reproduce
Uncertain but occurs after longer periods (4+ hrs)

## Links to any relevant pastes or documents 

Please post links to any relevant documents that might contain any extra information.

## Checklist

Use this checklist if you are using this issue as a tracker:

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3 ...

### PR DESCRIPTION
**Pull request by exhaustin**
# Description

Fixes #1383

### Changes
- Change error handling to account for different return types during read fail in newer pymodbus versions
- Add error code field in gripper state msg to indicate a read fail
- Pin pymodbus version

### Todos
- [ ] Test on hardware (Concern: how to repro read fail?)

## Type of change

Please check the options that are relevant.

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [ ] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change
- [ ] Datasets Release
- [ ] Models Release

## Type of requested review

- [x] I want a thorough review of the implementation.
- [ ] I want a high level review. 
- [ ] I want a deep design review.

# Testing

Tested on hardware, reproducing read fail by unplugging the USB connection to the Robotiq gripper.

### Before
Server side:
```
Traceback (most recent call last):
  File "/home/wangaustin/dev/fairo/polymetis/polymetis/python/scripts/launch_gripper.py", line 46, in main
    gripper_client.run()
  File "/home/wangaustin/dev/fairo/polymetis/polymetis/python/polymetis/robot_client/robotiq_gripper/robotiq_gripper_client.py", line 94, in run
    state = self.get_gripper_state()
  File "/home/wangaustin/dev/fairo/polymetis/polymetis/python/polymetis/robot_client/robotiq_gripper/robotiq_gripper_client.py", line 69, in get_gripper_state
    self.gripper.getStatus()
  File "/home/wangaustin/dev/fairo/polymetis/polymetis/python/polymetis/robot_client/robotiq_gripper/third_party/robotiq_2finger_grippers/robotiq_2f_gripper.py", line 64, in getStatus
    status = self.client.getStatus(6)
  File "/home/wangaustin/dev/fairo/polymetis/polymetis/python/polymetis/robot_client/robotiq_gripper/third_party/robotiq_2finger_grippers/robotiq_modbus_rtu/comModbusRtu.py", line 122, in getStatus
    output.append((response.getRegister(i) & 0xFF00) >> 8)
AttributeError: 'ModbusIOException' object has no attribute 'getRegister'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
(program terminates)

Client side:
```py
>>> gripper.get_state()
timestamp {
  seconds: 1665449135
  nanos: 304429000
}
width: 0.08500000089406967
```

### After
Server side:
```
[2022-10-10 17:42:35,257][polymetis.robot_client.robotiq_gripper.robotiq_gripper_client][WARNING] - Failed to read gripper state. Returning last observed state instead.
[2022-10-10 17:42:35,274][pymodbus.client.sync][ERROR] - [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
Modbus Error: [Connection] Failed to connect[ModbusSerialClient(rtu baud[115200])]
[2022-10-10 17:42:35,274][polymetis.robot_client.robotiq_gripper.robotiq_gripper_client][WARNING] - Failed to read gripper state. Returning last observed state instead.
[2022-10-10 17:42:35,290][pymodbus.client.sync][ERROR] - [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
Modbus Error: [Connection] Failed to connect[ModbusSerialClient(rtu baud[115200])]
[2022-10-10 17:42:35,290][polymetis.robot_client.robotiq_gripper.robotiq_gripper_client][WARNING] - Failed to read gripper state. Returning last observed state instead.
[2022-10-10 17:42:35,307][pymodbus.client.sync][ERROR] - [Errno 2] could not open port /dev/ttyUSB0: [Errno 2] No such file or directory: '/dev/ttyUSB0'
Modbus Error: [Connection] Failed to connect[ModbusSerialClient(rtu baud[115200])]
.
.
.
```
(program continues running, recovers when plugged back in)

Client side:
```py
>>> gripper.get_state()
timestamp {
  seconds: 1665449009
  nanos: 715200000
}
width: 0.08500000089406967
error_code: 1
```

# Checklist:

- [ ] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added relevant collaborators to review the PR before merge.
- [ ] [Polymetis only] I ran on hardware (1) all scripts in `tests/scripts`, (2) asv benchmarks.

### CODE REVIEW

**Review by 1heart — APPROVED** [review]
Nice, thanks.

Should we just pin the pymodbus version just in case?

**Comment by 1heart** [comment]
Oh also, does this actually solve the issue in #1383? The modbus getRegister exception is just a symptom of communication gone wrong, right?

**Comment by exhaustin** [comment]
> Oh also, does this actually solve the issue in #1383? The modbus getRegister exception is just a symptom of communication gone wrong, right?

I guess this issue can be separated into:
1. Gripper errors out on read fail instead of the original intended behavior: returning the last observed state. (Thus interrupting long-horizon data collection tasks)
2. Read fail returns the last observed state without any warning
3. The actual read fail

This PR resolves 1. and 2., but I don't have a good solution for 3. since it very rarely happens and is highly likely to be hardware/modbus issues.

**Comment by exhaustin** [comment]
Tested on hardware (see description for details). Merging to main.

**Pull request merged**
