### PR TITLE
bug fix for tokenizer, change _convert_token_to_id to convert_tokens_…

### PR DESCRIPTION
**Pull request by ruinianxu**
# Description

The method of ```_convert_token_to_id``` has been deprecated and changes to ```convert_tokens_to_ids ``` in the newer version of transformer. ```__getitem__``` in ```CAIPDataset``` hasn't been updated to this change.

Fixes # (issue)

## Type of change

Please check the options that are relevant.

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [ ] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change
- [ ] Datasets Release
- [ ] Models Release

## Type of requested review

- [x] I want a thorough review of the implementation.
- [ ] I want a high level review. 
- [ ] I want a deep design review.

## Before and After

**Before**
Screen Shot 2022-05-20 at 2 58 28 PM
**After**
Screen Shot 2022-05-20 at 3 00 54 PM

# Testing
If you don't have datasets under ```droidlet/artifacts```, you should run ```python agents/craftassist/craftassist_agent.py``` which will automatically download the dataset. 

Then under the root folder, run 
```
python tools/nsp_scripts/train_model.py --data_dir droidlet/artifacts/datasets/annotated_data/ --dtype_samples 'templated:.35;templated_filters:.05;annotated:.6' --tree_voc_file droidlet/artifacts/models/nlu/ttad_bert_updated/caip_test_model_tree.json --output_dir PATH_SAVING_MODELS
```
The training of NLU should be working now. 16GB memory might not be enough. In my case, reduce batch_size to 28 will address the issue of OUT_OF_CUDA_MEMORY.

# Checklist:

- [x] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [x] I have added relevant collaborators to review the PR before merge.
- [ ] [Polymetis only] I ran on hardware (1) all scripts in `tests/scripts`, (2) asv benchmarks.

### CODE REVIEW

**Review by ethan-carlson — APPROVED** [review]
Thanks for this PR!  This change works for me.  Please also update line 155 before merge.

**Comment by ruinianxu** [comment]
@ethan-carlson 
I've updated the method in Line 155. But currently training script doesn't support enabling tree_to_text flag. I've contacted Arthur and he said this part should be rewritten later.

**Comment by ethan-carlson** [comment]
> @ethan-carlson I've updated the method in Line 155. But currently training script doesn't support enabling tree_to_text flag. I've contacted Arthur and he said this part should be rewritten later.

OK, my recommendation would be to merge this PR with the known fix - replacing the deprecated method with the new one.  And then leave tree_to_text for the future.

**Review by kavyasrinet — APPROVED** [review]
Thanks for adding this bugfix in your first week!

**Pull request merged**
