### PR TITLE
[Polymetis] Adaptive joint PD (EE tracking improvement #2)

### PR DESCRIPTION
**Pull request by exhaustin**
# Description

Add adaptive joint PD that changes gains with respect to current joint pose to achieve constant end-effector dynamics. Gains are computed by the projecting the constant operational space controller gains to the joint space at each different joint pose.
The changes increase the end-effector tracking slightly, but more importantly cause the end-effector compliance to be isotropic and consistent across different joint poses (observed by exerting external forces on the end-effector).

Operational space PD:
image
Equivalent adaptive joint PD gains:
image

Hardware experiments show promising results when adding together the above adaptive gains with the original fixed gains (forming a "hybrid" controller). The current speculation is that the adaptive gains demonstrate consistent behaviors across different joint poses, but will sometimes result in insufficient gains to overcome friction within certain individual joints. The fixed joint gains help alleviate this issue by giving each joint a fixed, reasonable minimum gain at all times (effectively "normalizing" the adaptive gains).

### Changes
- Add a `HybridJointSpacePD` controller that utilizes both joint gains and operational space gains
- Modify `JointSpaceTrajectoryExecutor` (used by RobotInterface.move_to_joint_positions) to use the new controller
- Add `adaptive` argument to `RobotInterface.start_joint_impedance` as an option to use the new controller (turned off by default to not affect the current teleop workstreams that are using this function)

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [x] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change
- [ ] Datasets Release
- [ ] Models Release

## Type of requested review

- [x] I want a thorough review of the implementation.
- [ ] I want a high level review. 
- [ ] I want a deep design review.

## Before and After

If this PR introduces a change or fixes a bug, please add before and after screenshots (if this is causes a UX change) or before and after examples(this could be plain text, videos etc ) to demonstrate the change.

If this PR introduces a new feature, please also add examples or screenshots demonstrating the feature.

# Testing

Benchmark results from `benchmark_ee_tracking.py`:
```
=== Offline (move_to_joint_positions) tracking results ===
        Pos error(mm): mean=5.50, std=4.10, max=20.57
        Ori error(deg): mean=1.30, std=0.29, max=1.96
=== Offline (move_to_ee_pose) tracking results ===
        Pos error(mm): mean=41.94, std=14.13, max=66.34
        Ori error(deg): mean=6.74, std=1.68, max=9.09
=== Online (update_desired_ee_pose) tracking results ===
        Pos error(mm): mean=37.89, std=9.42, max=53.66
        Ori error(deg): mean=11.13, std=2.23, max=13.96
```

Improvements (compared to results in #1307) can be seen in the tracking performance of `move_to_joint_positions`, most notably the greatly decreased variance, demonstrating more consistent performance across different poses.
The EE pose commands were not affected by this PR.

# Checklist:

- [ ] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added relevant collaborators to review the PR before merge.
- [ ] [Polymetis only] I ran on hardware (1) all scripts in `tests/scripts`, (2) asv benchmarks.

### CODE REVIEW

**Review by 0wu — APPROVED** [review]
LGTM
The Hybrid controller algorithm and controller appears correct.
However, it's unclear to me if the trajectory tracking improvement simply comes from higher gains (from the addition) or better controller, as the original JointPD gains may not be optimized. An improvement analysis (another PR) is preferred.

**Comment by exhaustin** [comment]
> LGTM The Hybrid controller algorithm and controller appears correct. However, it's unclear to me if the trajectory tracking improvement simply comes from higher gains (from the addition) or better controller, as the original JointPD gains may not be optimized. An improvement analysis (another PR) is preferred.

Indeed it is highly likely that the improved tracking performance came from the increased gains. However, by pushing the EE around, the exhibited behavior is a lot more isotropic, which is desirable in most cases but hard to quantize. I should add this to the PR description.

**Review by 1heart — APPROVED** [review]
Cool, thanks!

**Comment by exhaustin** [comment]
> LGTM The Hybrid controller algorithm and controller appears correct. However, it's unclear to me if the trajectory tracking improvement simply comes from higher gains (from the addition) or better controller, as the original JointPD gains may not be optimized. An improvement analysis (another PR) is preferred.

Made an issue to keep track: #1336

**Pull request merged**
