### PR TITLE
Enable memory_2d map for Craftassist Agent

### PR DESCRIPTION
**Pull request by aqibisbiqa**
# Description

(Fresh version of [earlier PR](https://github.com/facebookresearch/fairo/pull/1180))
The map that displays in the in the memory_2d pane for the Locobot agent was not previously implemented for the Craftassist agent. With this PR, we can now see the agent, obstacles from the obstacle map, and other detected objects as points plotted on the map pane.

Fixes # (issue)

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [x] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change
- [ ] Datasets Release
- [ ] Models Release

## Type of requested review

- [x] I want a thorough review of the implementation.
- [ ] I want a high level review. 
- [ ] I want a deep design review.

## Before and After

Before:
Screen Shot 2022-05-20 at 4 26 50 PM

After:
Screen Shot 2022-06-07 at 2 49 58 PM

# Testing

You can see a map :) And the agent program + dashboard doesn't break when rendering the map after a multitude of test commands. This diff won't affect any of the previously implemented unit tests, and it seems to pass all of the existing ones.

Oftentimes you'll only see the bot marker on the map, you can populate the agent's perceived obstacle map by issuing a command. For example, to produce the 'After' picture, run your cuberite instance with command `python droidlet/lowlevel/minecraft/cuberite_process.py --config really_flat_world` and issue the command `move three steps left`.

# Checklist:

- [x] I have performed manual end-to-end testing of the feature in my environment.
- [x] I have added Docstrings and comments to the code.
- [x] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [x] I have added relevant collaborators to review the PR before merge.
- [ ] [Polymetis only] I ran on hardware (1) all scripts in `tests/scripts`, (2) asv benchmarks.

### CODE REVIEW

**Review by ys1382fb — APPROVED** [review]
image

**Comment by ethan-carlson** [comment]
This looks great!  I'm excited to see where this is headed.  One thing I notice (maybe to be addressed later on) is that the map is small compared to the world.  For instance, if you issue a "build a ___" command, the standard place the agent goes to build it is off the map.  Is there a plan for scrolling or resizing later on?

Also, after having the agent build something near me ("build a cube near me"), on the map, it didn't show up, but it should right?  It's definitely a reference object in memory...

**Comment by aqibisbiqa** [comment]
> This looks great! I'm excited to see where this is headed. One thing I notice (maybe to be addressed later on) is that the map is small compared to the world. For instance, if you issue a "build a ___" command, the standard place the agent goes to build it is off the map. Is there a plan for scrolling or resizing later on?

That's a pretty interesting idea. I tried resolving that by expanding the size of the map, but messing with the aspect ratio of the map apparently results in some bugs for the LocoBot (and probably Craftassist) as detailed [here](https://github.com/facebookresearch/fairo/pull/1074). I'll look into it going forward

> Also, after having the agent build something near me ("build a cube near me"), on the map, it didn't show up, but it should right? It's definitely a reference object in memory...

I've been trying to resolve this issue for some time now. The `get_detected_objects_for_map` method doesn't seem to obtain the right values when querying. Obviously a critical error, but this PR is just for enabling us to see the map. When I was fiddling with the memory methods, I found one method that wasn't adding blocks to memory when the agent placed them, so the issue likely lies with that

**Review by kavyasrinet — APPROVED** [review]
This PR looks good, let's definitely look into the aspect ratio of the map once this is merged in. 
Any idea why we see changes in the file: `polymetis/polymetis/src/clients/franka_panda_client/third_party/libfranka` in this PR ? 
Have we rebased on main ?

**Review by snyxan — APPROVED** [review]

**Pull request merged**
