### PR TITLE
[Polymetis] Refactor planning & Cartesian control

### PR DESCRIPTION
**Pull request by exhaustin**
Stacked PR on top of #758

### Previous nested module structure
```
JointSpacePD < JointImpedanceControl < JointPlanExecutor < JointSpaceMoveTo
                                                         < CartesianTargetJointMoveTo
CartesianSpacePDFast < CartesianImpedanceControl < CartesianSpaceMoveTo
```

Planners are "planning modules" within `toco.modules`

### New nested module structure
```
JointSpacePD < JointImpedanceControl
             < JointTrajectoryExecutor < JointSpaceMoveTo
                                       < CartesianTargetJointMoveTo
CartesianSpacePDFast < CartesianImpedanceControl
                     < EndEffectorTrajectoryExecutor < CartesianSpaceMoveTo

```

Planners are callable functions within `toco.planning`

### CODE REVIEW

**Review by 1heart — APPROVED** [review]
If I can summarize the logic, it's just that the `.*ImpedanceControl` modules can generate the plan and save it using `toco.planning.*` functions without a `.*TrajectoryExecutor`, correct?

**Comment by exhaustin** [comment]
> If I can summarize the logic, it's just that the `.*ImpedanceControl` modules can generate the plan and save it using `toco.planning.*` functions without a `.*TrajectoryExecutor`, correct?

A better summary would be:
- `.*ImpedanceControl` are policies that stabilize around a fixed state that can be updated
- `.*TrajectoryExecutor` are policies that stabilize around a given trajectory given as a list of states during initialization
- `toco.planning.*` provide helper functions that generate these trajectories from parameters

**Comment by 1heart** [comment]
Okay, I think the structure that makes semantic sense.

I'm not 100% sure how much simpler this is -- it seems to me that the `MoveTo` policies are still thin layers around `JointTrajectoryExecutor`. Is there another layer of indirection we can remove? Maybe `JointTrajectoryExecutor` can just take in a flag for joint or cartesian planning? Just thinking out loud, since we're taking the time to refactor.

**Comment by exhaustin** [comment]
No yeah it's great to iterate on this since I agree it still seems complicated to me.

> I'm not 100% sure how much simpler this is

Currently I made the tradeoff of having some code duplication and omitting one structural layer (between `.*ImpedanceControl` and `.*TrajectoryExecutor`

> it seems to me that the `MoveTo` policies are still thin layers around `JointTrajectoryExecutor`.

Indeed, and after thinking about it I'm going to omit the `MoveTo` policies, since anyone looking to move to a specific pose would be better off using the macros in `RobotInterface` instead of instantiating the custom policies. This will make `RobotInteface` methods slightly longer.


> Is there another layer of indirection we can remove? Maybe `JointTrajectoryExecutor` can just take in a flag for joint or cartesian planning?

I would like to keep the `.*TrajectoryExecutor` layer and exclude planning from it. The reason being: in addition to joint space and cartesian space min-jerk policies, I'm working on a moveit planner integration that would output a trajectory that avoids obstacles. More joint movement plans like this could also be included in the future (such as DMPs), and thus we might have to keep adding flags to the trajectory executors, which wouldn't be sustainable.

**Comment by 1heart** [comment]
That sounds reasonable to me, thanks!

**Pull request merged**
