### PR TITLE
Update sets

### PR DESCRIPTION
**Pull request by aszlam**
# Description

makes Set memories functional, adds a test for them
Along the way fixes some unfinished business from moving ordinals in selector DSL; a lot of stuff is cleaner and more "properly" done.  in particular, ordinals work more reliably across selectors

## Type of change

Please check the options that are relevant.

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [x] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change
- [ ] Datasets Release
- [ ] Models Release

## Type of requested review

- [x] I want a thorough review of the implementation.
- [ ] I want a high level review. 
- [ ] I want a deep design review.

## Before and After

previously, Set memories weren't used- now we can use them with a put memory to bundle some memories into a set.
also, ordinals are (more) properly used in selectors

# Checklist:

- [ ] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [x] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [x] New and existing unit tests pass locally with my changes.
- [ ] I have added relevant collaborators to review the PR before merge.
- [ ] [Polymetis only] I have verified that all scripts in `tests/scripts` runs on hardware.

### CODE REVIEW

**Review by kavyasrinet — APPROVED** [review]
The changes LGTM.
Can we also add an additional test to test the ordinal change ?

**Comment by aszlam** [comment]
> The changes LGTM.
> Can we also add an additional test to test the ordinal change ?

its at least implicitly tested in the put_memory Set test (bc it requires precisely two things to be retrieved).  Do you want a separate test?

**Comment by kavyasrinet** [comment]
Yes one more explicit test for ordinals, please :)

**Comment by aszlam** [comment]
ok, I am just going to merge this, and if you want will add more ordinal tests in separate PR

**Comment by kavyasrinet** [comment]
Thanks!

**Comment by aszlam** [comment]
lol
just saw comment
will add test now

**Pull request merged**
