### PR TITLE
[Polymetis] Fix spdlog dependency break

### PR DESCRIPTION
**Pull request by exhaustin**
# Description

Yet another issue due to an updated dependency.
The [spdlog conda package](https://anaconda.org/conda-forge/spdlog/files) was updated on Oct 21st, causing [linking issues](https://pastebin.com/tz7waK6z).
This is not an issue of different build vs. run spdlog versions, as using the newer spdlog to build & run still results in the same issue.

The PR simply pins the spdlog dependency to the older, stable build.

## Type of change

Please check the options that are relevant.

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [ ] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change
- [ ] Datasets Release
- [ ] Models Release

## Type of requested review

- [ ] I want a thorough review of the implementation.
- [x] I want a high level review. 
- [ ] I want a deep design review.

## Before and After

If this PR introduces a change or fixes a bug, please add before and after screenshots (if this is causes a UX change) or before and after examples(this could be plain text, videos etc ) to demonstrate the change.

If this PR introduces a new feature, please also add examples or screenshots demonstrating the feature.

# Testing

Please describe the tests that you ran to verify your changes and how we can reproduce.

# Checklist:

- [ ] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added relevant collaborators to review the PR before merge.
- [ ] [Polymetis only] I ran on hardware (1) all scripts in `tests/scripts`, (2) asv benchmarks.

### CODE REVIEW

**Review by 1heart — APPROVED** [review]
Thanks!

**Comment by exhaustin** [comment]
[pytest-benchmark](https://github.com/ionelmc/pytest-benchmark/actions) is currently broken. Will wait a bit to see if the issue is fixed then rerun tests / merge.

**Comment by 1heart** [comment]
Maybe let's just pin pytest-benchmark to <4.0.0?

**Comment by 1heart** [comment]
Are they just never fixing pytest-benchmark? 😂

**Comment by AlexanderKhazatsky** [comment]
Just a heads up, I think in this push the building from source, ./scripts/build_libfranka.sh <version_tag_or_commit_hash> stuff doesn't work anymore. When I installed as usual I got the following error, and it was fixed when i built libfranka mysself and checked out 0.8.0 manually.


(polymetis-local) sasha@watney:~$ launch_robot.py robot_client=franka_hardware
Warning: Failed to load 'libtorchscript_pinocchio.so' from CONDA_PREFIX, loading from default build directory instead: '/home/sasha/fairo/polymetis/polymetis/build/torch_isolation/libtorchscript_pinocchio.so'
Warning: Failed to load 'libtorchrot.so' from CONDA_PREFIX, loading from default build directory instead: '/home/sasha/fairo/polymetis/polymetis/build/torch_isolation/libtorchrot.so'
/home/sasha/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/hydra/plugins/config_source.py:190: UserWarning: 
Missing @package directive robot_client/franka_hardware.yaml in pkg://polymetis.conf.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/adding_a_package_directive
  warnings.warn(message=msg, category=UserWarning)
[2022-11-04 19:12:25,190][__main__][INFO] - Adding /home/sasha/fairo/polymetis/polymetis/build to $PATH
[2022-11-04 19:12:25,190][__main__][INFO] - Starting server
[2022-11-04 19:12:25,190][__main__][INFO] - Acquiring sudo...
"Acquired sudo."
[2022-11-04 19:12:25.296] [info] Using real time: true
[2022-11-04 19:12:25.296] [info] Using server address: 0.0.0.0:50051
Using 20MB as stack size
Using 80 as real-time thread priority
Using 0 as cpu_dma_latency
Disabled sbrk...
Disabled mmap...
Locked memory...
Initialized pthread...
Finished setting stacksize...
Finished setting scheduling policy & priority...
Creating thread...
Started realtime thread.
[2022-11-04 19:12:25.385] [info] Server listening on 0.0.0.0:50051
[2022-11-04 19:12:25,406][__main__][INFO] - Starting robot client...
[2022-11-04 19:12:25,614][polymetis.robot_client.executable_robot_client][INFO] - === Config: ===
robot_ip: 172.16.0.8
control_ip: 0.0.0.0
control_port: 50051
readonly: false
mock: false
use_real_time: true
hz: 1000
num_dofs: 7
exec: franka_panda_client
robot_client_metadata_path: /tmp/tmpkx4k5pau
limit_rate: true
lpf_cutoff_frequency: 100
limits:
  cartesian_pos_upper:
  - 1.0
  - 0.4
  - 1.0
  cartesian_pos_lower:
  - 0.1
  - -0.4
  - -0.05
  joint_pos_upper:
  - 2.8
  - 1.66
  - 2.8
  - -0.17
  - 2.8
  - 3.65
  - 2.8
  joint_pos_lower:
  - -2.8
  - -1.66
  - -2.8
  - -2.97
  - -2.8
  - 0.08
  - -2.8
  joint_vel:
  - 2.075
  - 2.075
  - 2.075
  - 2.075
  - 2.51
  - 2.51
  - 2.51
  elbow_vel: 2.075
  joint_torques:
  - 86.0
  - 86.0
  - 86.0
  - 86.0
  - 11.5
  - 11.5
  - 11.5
collision_behavior:
  lower_torque:
  - 40.0
  - 40.0
  - 40.0
  - 40.0
  - 40.0
  - 40.0
  - 40.0
  upper_torque:
  - 40.0
  - 40.0
  - 40.0
  - 40.0
  - 40.0
  - 40.0
  - 40.0
  lower_force:
  - 40.0
  - 40.0
  - 40.0
  - 40.0
  - 40.0
  - 40.0
  upper_force:
  - 40.0
  - 40.0
  - 40.0
  - 40.0
  - 40.0
  - 40.0
safety_controller:
  is_active: true
  margins:
    cartesian_pos: 0.05
    joint_pos: 0.2
    joint_vel: 0.5
  stiffness:
    cartesian_pos: 200.0
    joint_pos: 50.0
    joint_vel: 20.0

[2022-11-04 19:12:25,615][polymetis.robot_client.executable_robot_client][INFO] - === Executing client at /home/sasha/fairo/polymetis/polymetis/build/franka_panda_client ===
Using 20MB as stack size
Using 80 as real-time thread priority
Using 0 as cpu_dma_latency
Disabled sbrk...
Disabled mmap...
Locked memory...
Initialized pthread...
Finished setting stacksize...
Finished setting scheduling policy & priority...
Creating thread...
Started realtime thread.
[2022-11-04 19:12:25.650] [info] ==== Initializing new RobotClient... ====
[2022-11-04 19:12:25.742] [info] Success.
[2022-11-04 19:12:25.743] [info] Connecting to Franka Emika...
terminate called after throwing an instance of 'franka::IncompatibleVersionException'
  what():  libfranka: Incompatible library version (server version: 4, library version: 5). Please check https://frankaemika.github.io for Panda system updates or use a different version of libfranka.
Traceback (most recent call last):
  File "/home/sasha/fairo/polymetis/polymetis/python/scripts/launch_robot.py", line 84, in main
    client.run()
  File "/home/sasha/fairo/polymetis/polymetis/python/polymetis/robot_client/executable_robot_client.py", line 78, in run
    subprocess.run(
  File "/home/sasha/anaconda3/envs/polymetis-local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', 'env', '"PATH=$PATH"', '/home/sasha/fairo/polymetis/polymetis/build/franka_panda_client', '/tmp/tmpha5r2lqj']' died with <Signals.SIGABRT: 6>.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[2022-11-04 19:12:25,905][__main__][INFO] - Using sudo to kill subprocess with pid 12134, pgid 12134...

**Pull request merged**
